### ISSUE TITLE
Verification fails with java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#341]
> Created by **@fpoli** on 2018-05-31 16:31
> Last updated on 2019-07-29 14:43

The attached program passes the consistency checks, but causes a `java.util.NoSuchElementException: head of empty list` during the verification.

Part of the stacktrace:
```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at viper.silicon.rules.executor$.viper$silicon$rules$executor$$follow(Executor.scala:54)
	at viper.silicon.rules.executor$$anonfun$viper$silicon$rules$executor$$follows$1.apply(Executor.scala:89)
	at viper.silicon.rules.executor$$anonfun$viper$silicon$rules$executor$$follows$1.apply(Executor.scala:87)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at viper.silicon.rules.executor$.viper$silicon$rules$executor$$follows(Executor.scala:87)
	at viper.silicon.rules.executor$$anonfun$exec$1.apply(Executor.scala:107)
	at viper.silicon.rules.executor$$anonfun$exec$1.apply(Executor.scala:106)
	at viper.silicon.rules.executor$.execs(Executor.scala:206)
	at viper.silicon.rules.executor$$anonfun$execs$1.apply(Executor.scala:204)
	at viper.silicon.rules.executor$$anonfun$execs$1.apply(Executor.scala:203)
	at viper.silicon.rules.executor$$anonfun$exec$7.apply(Executor.scala:214)
	at viper.silicon.rules.executor$$anonfun$exec$7.apply(Executor.scala:212)
	at viper.silicon.rules.executor$$anonfun$5.apply(Executor.scala:223)
	at viper.silicon.rules.executor$$anonfun$5.apply(Executor.scala:222)
	at viper.silicon.rules.executor$$anonfun$6.apply(Executor.scala:253)
	at viper.silicon.rules.executor$$anonfun$6.apply(Executor.scala:251)
        ...
```

Silicon build that I'm using: `Silicon version 1.1-SNAPSHOT <https://github.com/viperproject/silicon/commit/aa2bfca33b4181126d0626cf4809d8d5ce40d76a> default 2018/05/30 01:48:53`

---

Attachments:
* [**`program.vpr`**](https://gist.githubusercontent.com/viper-admin/99eb08edd65a95b245bc0b61af4628c4/raw/35a53d26c3d80a2f64e65b889f55839c2bbbe135/program.vpr)
* [**`check.dot.pdf`**](https://gist.githubusercontent.com/viper-admin/99eb08edd65a95b245bc0b61af4628c4/raw/d11d1699a1966599e39927edcb7b112878624274/check.dot.pdf)

**Comment by mschwerhoff** [comment]
@dohrau Any progress on this?
