### ISSUE TITLE
Regression: Crash with Unit snapshot cannot be decomposed

### ISSUE THREAD

**Issue by vakaras** [viperproject/silicon#592]
The following program (I will try to minimize it later, a bit too late evening for debugging now):

```viper
domain MirrorDomain {

  function mirror_simple$m_is_some__$TY$__(_1: Snap$m_MyOption$_beg_$_end_): Bool
}

domain Snap$m_MyOption$_beg_$_end_ {

  function discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(self: Snap$m_MyOption$_beg_$_end_): Int

  function cons$0$__$TY$__Snap$m_MyOption$_beg_$_end_$(): Snap$m_MyOption$_beg_$_end_

  function cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_0: Int): Snap$m_MyOption$_beg_$_end_

  function Snap$m_MyOption$_beg_$_end_$1$field$f$0__$TY$__(self: Snap$m_MyOption$_beg_$_end_): Int

  axiom Snap$m_MyOption$_beg_$_end_$discriminant_range {
    (forall self: Snap$m_MyOption$_beg_$_end_ :: { discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(self) } 0 <= discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(self) && discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(self) <= 1)
  }

  axiom Snap$m_MyOption$_beg_$_end_$0$discriminant_axiom {
    discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(cons$0$__$TY$__Snap$m_MyOption$_beg_$_end_$()) == 0
  }

  axiom Snap$m_MyOption$_beg_$_end_$1$injectivity {
    (forall _l_0: Int, _r_0: Int :: { cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_l_0),cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_r_0) } cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_l_0) == cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_r_0) ==> _l_0 == _r_0)
  }

  axiom Snap$m_MyOption$_beg_$_end_$1$discriminant_axiom {
    (forall _0: Int :: { cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_0) } discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_0)) == 1)
  }

  axiom Snap$m_MyOption$_beg_$_end_$1$field$f$0$axiom {
    (forall _0: Int :: { Snap$m_MyOption$_beg_$_end_$1$field$f$0__$TY$__(cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_0)) } Snap$m_MyOption$_beg_$_end_$1$field$f$0__$TY$__(cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(_0)) == _0)
  }

  axiom Snap$m_MyOption$_beg_$_end_$1$field$f$0$valid {
    (forall self: Snap$m_MyOption$_beg_$_end_ :: { Snap$m_MyOption$_beg_$_end_$1$field$f$0__$TY$__(self) } -2147483648 <= Snap$m_MyOption$_beg_$_end_$1$field$f$0__$TY$__(self) && Snap$m_MyOption$_beg_$_end_$1$field$f$0__$TY$__(self) <= 2147483647)
  }
}

field discriminant: Int

field enum_Some: Ref

field f$0: Ref

field val_int: Int

function builtin$unreach__$TY$__$bool$$(): Bool
  requires false


function m_MyOption$_beg_$_end_$$discriminant$$__$TY$__(self: Ref): Int
  requires acc(m_MyOption$_beg_$_end_(self), read$())
  ensures 0 <= result && result <= 1
  ensures discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(snap$__$TY$__Snap$m_MyOption$_beg_$_end_$(self)) == result
{
  (unfolding acc(m_MyOption$_beg_$_end_(self), read$()) in self.discriminant)
}

function m_is_some__$TY$__(_1: Snap$m_MyOption$_beg_$_end_): Bool
  requires true
  requires true
  ensures true
  ensures [result == mirror_simple$m_is_some__$TY$__(_1), true]
{
  discriminant$__$TY$__Snap$m_MyOption$_beg_$_end_$(_1) == 1
}

function snap$__$TY$__Snap$m_MyOption$_beg_$_end_$(self: Ref): Snap$m_MyOption$_beg_$_end_
  requires acc(m_MyOption$_beg_$_end_(self), read$())
{
  (unfolding acc(m_MyOption$_beg_$_end_(self), read$()) in (self.discriminant == 1 ? (unfolding acc(m_MyOption$_beg_$_end_Some(self.enum_Some), read$()) in (unfolding acc(i32(self.enum_Some.f$0), read$()) in cons$1$__$TY$__Snap$m_MyOption$_beg_$_end_$(self.enum_Some.f$0.val_int))) : cons$0$__$TY$__Snap$m_MyOption$_beg_$_end_$()))
}

function read$(): Perm
  ensures none < result
  ensures result < write


predicate DeadBorrowToken$(borrow: Int)

predicate i32(self: Ref) {
  acc(self.val_int, write)
}

predicate m_MyOption$_beg_$_end_(self: Ref) {
  acc(self.discriminant, write) && (0 <= self.discriminant && self.discriminant <= 1 && (acc(self.enum_Some, write) && (self.discriminant == 1 ==> acc(m_MyOption$_beg_$_end_Some(self.enum_Some), write))))
}

predicate m_MyOption$_beg_$_end_Some(self: Ref) {
  acc(self.f$0, write) && acc(i32(self.f$0), write)
}

predicate tuple0$(self: Ref) {
  true
}

method m_test() returns (_0: Ref)
{
  var __t0: Bool
  var __t1: Bool
  var _1: Ref
  var _2: Ref
  label start
  // ========== start ==========
  // Def path: "issue_362::test"
  // Span: /home/data/eth/rust/prusti-dev/prusti-tests/tests/verify/pass/issues/issue-362.rs:23:1: 25:2 (#0)
  __t0 := false
  __t1 := false
  // Preconditions:
  label pre
  // ========== bb0 ==========
  __t0 := true
  // [mir] StorageLive(_1)
  // [mir] StorageLive(_2)
  // [mir] _2 = MyOption::None
  _2 := builtin$havoc_ref()
  inhale acc(m_MyOption$_beg_$_end_(_2), write)
  inhale m_MyOption$_beg_$_end_$$discriminant$$__$TY$__(_2) == 0
  // [mir] _1 = MyOption::map(move _2) -> [return: bb1, unwind: bb2]
  label l0

// HERE:
  assert !m_is_some__$TY$__(snap$__$TY$__Snap$m_MyOption$_beg_$_end_$(_2)) || ((unfolding acc(m_MyOption$_beg_$_end_(_2), write) in _2.discriminant) == 0 ? builtin$unreach__$TY$__$bool$$() : (unfolding acc(m_MyOption$_beg_$_end_(_2), write) in 5 == (unfolding acc(m_MyOption$_beg_$_end_(_2), write) in (unfolding acc(m_MyOption$_beg_$_end_Some(_2.enum_Some), write) in (unfolding acc(i32(_2.enum_Some.f$0), write) in _2.enum_Some.f$0.val_int)))))
  assert true
  exhale acc(m_MyOption$_beg_$_end_(_2), write)
  _1 := builtin$havoc_ref()
  inhale acc(m_MyOption$_beg_$_end_(_1), write)
  inhale true
  label l1
  // ========== bb1 ==========
  __t1 := true
  // [mir] StorageDead(_2)
  // [mir] StorageDead(_1)
  // [mir] _0 = const ()
  // [mir] return
  // ========== return ==========
  // Target of any 'return' statement.
  // Exhale postcondition
  label l3
  // Fold predicates for &mut args and transfer borrow permissions to old
  // Fold the result
  fold acc(tuple0$(_0), write)
  // obtain acc(tuple0$(_0), write)
  // Assert possible strengthening
  // Assert functional specification of postcondition
  // Assert type invariants
  assert true
  // Exhale permissions of postcondition (1/3)
  // Exhale permissions of postcondition (2/3)
  exhale acc(tuple0$(_0), write)
  // Exhale permissions of postcondition (3/3)
  goto end_of_method
  label end_of_method
}

method builtin$havoc_bool() returns (ret: Bool)


method builtin$havoc_int() returns (ret: Int)


method builtin$havoc_ref() returns (ret: Ref)

```

causes the following crash when verified in Silicon with `--enableMoreCompleteExhale`:
```
Exception in thread "main" java.lang.AssertionError: assertion failed: Unit snapshot cannot be decomposed                                                                                                  
        at scala.Predef$.assert(Predef.scala:280)                                                    
        at viper.silicon.supporters.DefaultSnapshotSupporter.createSnapshotPair(SnapshotSupporter.scala:130)
        at viper.silicon.supporters.DefaultSnapshotSupporter.createSnapshotPair(SnapshotSupporter.scala:107)
        at viper.silicon.rules.producer$.produceTlcs(Producer.scala:150)                             
        at viper.silicon.rules.producer$.produceR(Producer.scala:174)           
        at viper.silicon.rules.producer$.produce(Producer.scala:107)                                 
        at viper.silicon.rules.evaluator$.$anonfun$eval2$81(Evaluator.scala:770)                     
        at viper.silicon.rules.consumer$.$anonfun$consume$1(Consumer.scala:78)                       
        at viper.silicon.rules.executionFlowController$.$anonfun$tryOrFail2$3(ExecutionFlowController.scala:160)
        at viper.silicon.rules.executionFlowController$.$anonfun$tryOrFailWithResult$1(ExecutionFlowController.scala:119)
        at viper.silicon.rules.executionFlowController$.$anonfun$tryOrFail2$2(ExecutionFlowController.scala:160)
… // Many more lines
```

I suspect that the problem is caused by the assert marked with `HERE`.

The test verifies fine with this [Viper IDE release](https://github.com/viperproject/viper-ide/releases/tag/v-2022-01-22-0738) and fails with [this one](https://github.com/viperproject/viper-ide/releases/tag/v-2022-01-29-0732). Since Silicon CI was also failing when the second release was created, probably it is worth fixing it first before investigating this issue.

cc @Aurel300 I think this bug is a blocker for the Viper release.

**Comment by mschwerhoff** [comment]
I locally ran Silicon f963fae2 with `--enableMoreCompleteExhale` on the code above, but did not get an exception. The CI failure is (most likely) unrelated.

Can you locally reproduce the problem?

**Comment by vakaras** [comment]
> Can you locally reproduce the problem?

Yes.

> If so, please have a look at [these changes](https://github.com/viperproject/silicon/commit/21fd6007b762af8cbda76d6f061499b27fa881fe#diff-eb676c350e496d17b2a281bcea8e755997ea55eb22d7ad3514990e090fee5d36L76), and try the recently removed lines 87-89 (left) instead of the added line 88 (right).

The following seems to fix the crash:

```scala
          //Q(s2, h2, Unit, v2)
          val fresh = v2.decider.fresh(sorts.Snap)
          val s3 = s2.copy(functionRecorder = s2.functionRecorder.recordFreshSnapshot(fresh.applicable))
          Q(s3, h2, fresh, v2)
```

**Comment by mschwerhoff** [comment]
Feel free to push the change right away. It should be self-contained.
